myapp/website/forms/contactform.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    name = StringField("Full name", validators=[DataRequired()])
    email = EmailField("Email", validators=[DataRequired(), Email()])
    phone = StringField("Phone number")
    message = TextAreaField("Message", validators=[DataRequired()])
    submit = SubmitField("Submit")

myapp/website/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from myapp.website.forms.contactform import ContactForm
from myapp.msgraphapi import MSGraphAPI
from config import Config

website_bp = Blueprint(
    'website_bp',
    __name__,
    template_folder='templates',
    static_folder='static',
)


@website_bp.route('/', methods=['GET', 'POST'])
def home():
    form = ContactForm()
    if request.method == 'POST':
        html = render_template("ws_contact_email.html", form=form)
        subject = "Thank you for reaching out to Mozer Consulting"

        mail_api = MSGraphAPI()
        mail_api.send_email(
            subject=subject,
            body=html,
            to_recipients=[request.form.get('email')],
            cc_recipients=[Config.UPN]
        )
        flash("Your message has been sent successfully!", 'success')
        return redirect(url_for('website_bp.home') + "#top")
    return render_template('ws_index.html', form=form)


@website_bp.route('/copyright')
def my_copyright():
    return render_template('ws_copyright.html')


@website_bp.route('/disclaimer')
def disclaimer():
    return render_template('ws_disclaimer.html')


@website_bp.route('/terms')
def terms():
    return render_template('ws_terms.html')


@website_bp.route('/privacy')
def privacy():
    return render_template('ws_privacy.html')

myapp/website/templates/ws_about.html
<section id="about">
  <div class="container mt-4">
      <h2 class="mt-4 pb-2 border-bottom"><img class="me-3" src="{{ url_for('static', filename='/img/svg/person-vcard.svg') }}"> About me</h2>
  </div>


  <div class="container py-5">
    <div class="main-timeline-2">
      <div class="timeline-2 left-2">
        <div class="card">
          <img src="{{ url_for('static',filename='/img/artwork_school_is_over.webp')}}" class="card-img-top"
            alt="Responsive image">
          <div class="card-body p-4">
            <h4 class="fw-bold mb-4">School is over</h4>
            <p class="text-muted mb-4"><i class="far fa-clock" aria-hidden="true"></i> 1998 - 1999</p>
            <p class="mb-0">
              After finishing school in 1998 (Bachelor of Business Administration) I started my first job at
              Baan Business Innovation. Here we developed methodologies and tools to simplify and speed-up ERP
              implementations. Looking back, this job defined the direction of my career – aligning people,
              processes, systems and data. I realized however that I needed to develop additional skills
              and wanted to see different companies.
            </p>
          </div>
        </div>
      </div>
      <div class="timeline-2 right-2">
        <div class="card">
          <img src="{{ url_for('static',filename='/img/artwork_trainee.webp') }}" class="card-img-top"
            alt="Responsive image">
          <div class="card-body p-4">
            <h4 class="fw-bold mb-4">Management Trainee</h4>
            <p class="text-muted mb-4"><i class="far fa-clock" aria-hidden="true"></i> 1999 - 2001</p>
            <p class="mb-0">
              In 1999 I started a two year Management Trainee-ship at Ormit. My first eight month assignment was
              at Royal Dutch Airforce in a PMO role. After that I got my hands dirty on SAP for the first time at ASML.
              As a member of the New Product Introduction team I worked hands-on with SAP to provide logistics support
              to a development team from design to mass production phase. For my last assignment I joined a European
              SAP implementation project for the ambient food and margarine division at Unilever. This is where I found
              my calling!
            </p>
          </div>
        </div>
      </div>
      <div class="timeline-2 left-2">
        <div class="card">
          <img src="{{ url_for('static',filename='/img/artwork_fmcg.webp') }}" class="card-img-top"
            alt="Responsive image">
          <div class="card-body p-4">
            <h4 class="fw-bold mb-4">The Unilever years</h4>
            <p class="text-muted mb-4"><i class="far fa-clock" aria-hidden="true"></i> 2001 - 2008</p>
            <p class="mb-2">
              When I left Ormit I joined Unilever to continue working on the previously mentioned project as an inhouse
              consultant. In 2003, after successful implementations in The Netherlands, Sweden and Finland, I was asked
              to join Unilever NL as a team lead in the Supply & Demand Planning department. This was an amazing
              experience, but after two years I realized SAP consulting and project work is what I wanted to do.
            </p>
            <p class="mb-2">
              In 2005 I re-joined the European SAP project. A year later Unilever decided to outsource the project
              to Accenture. I transferred to Accenture but after six years at Unilever I wanted to broaden my
              horizon and see other companies. I joined ITVisors in 2007, but I was immediately hired back to
              Accenture to continue my work at Unilever. Only in 2008 I said goodbye to Unilever after having
              implemented SAP in 15 countries.
            </p>
          </div>
        </div>
      </div>
      <div class="timeline-2 right-2">
        <div class="card">
          <img src="{{ url_for('static',filename='/img/artwork_sap_consulting.webp') }}" class="card-img-top"
            alt="Responsive image">
          <div class="card-body p-4">
            <h4 class="fw-bold mb-4"> SAP consultant @ Magnus</h4>
            <p class="text-muted mb-4"><i class="far fa-clock" aria-hidden="true"></i> 2007 - 2018</p>
            <p class="mb-2">
              After a successful project at Evonik together with Improvium it was time to leave ITVisors.
              In 2009 I joined Magnus as Senior SAP Consultant in the logistics area and from 2012 till 2018
              I lead the logistics practice as Managing Consultant. During my Magnus period I worked on challenging
              projects.
            </p>
            <p class="mb-2">
              At Tata Steel we redesigned and harmonized the production planning and shopfloor control
              processes.
            </p>
            <p class="mb-2">
              At AkzoNobel I worked on an amazing project to implement a tax efficient supply chain. With the help
              of SAP System Landscape Optimization (SLO) we completely changed the enterprise structure.
            </p>
            <p class="mb-2">
              A greenfield SAP implementation at Koninklijke Jaarbeurs including a Mendix webshop with SAP integration.
            </p>
          </div>
        </div>
      </div>
      <div class="timeline-2 left-2">
        <div class="card">
          <img src="{{ url_for('static',filename='/img/artwork_moco.png') }}" class="card-img-top"
            alt="Responsive image">
          <div class="card-body p-4">
            <h4 class="fw-bold mb-4">Mozer Consulting</h4>
            <p class="text-muted mb-4"><i class="far fa-clock" aria-hidden="true"></i> 2018 - Now</p>
            <p class="mb-2">
              End of 2017 I felt it was time for the next step and on March 1st, 2018 Mozer Consulting was born.
              My first assignment was a global integration project at NXP Semiconductors. In 16 months we successfully
              integrated the former Freescale Semiconductors production facilities in Arizona, Texas, Malaysia and
              China in the NXP SAP system.
            </p>
            <p class="mb-2">
              In october 2020 I joined PVH Europe to prepare for the impact of BREXIT on the Order to Cash processes
              in Retail, Wholesale and E-Commerce flows.
            </p>
            <p class="mb-2">
              In april 2021 I joined Deloitte as workstream lead for a greenfield SAP S/4HANA implementation at
              Teijin Aramid. My team was responsible for inventory and warehouse management, all intra- and
              intercompany goodsflows, transportation management and toll-manufacturing. After successful deployment
              in two factories and preparations for the third one I left in april 2023 to go back to NXP.
            </p>
            <p class="mb-2">
              I joined NXP Semiconductors for a challenging brownfield SAP S/4HANA implementation going live with
              a big-bang in january 2024.
            </p>
          </div>
      </div>
    </div>
    </div>
  </div>
</section>

myapp/website/templates/ws_copyright.html
{% extends "base.html" %}

{% block favicon %}
    <link rel="icon" href="{{ url_for('static', filename='img/logo_moco.ico') }}" type="image/x-icon" />
{% endblock %}

{% block custom_styles %}

{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block title %}Mozer Consulting - Copyright Notice{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block header %}
    {% include 'ws_navbar.html' %}
{% endblock %}

{% block main %}
<div class="container rounded-3 mt-5"> <!-- Main container -->

	<div class="row"> <!-- Row for page title -->
		<div class="col-12 my-2"> <!-- Col for page title -->
			<h3>Copyright Notice</h3>
			<hr>
		</div> <!-- Col for page title -->
	</div> <!-- Row for page title -->

    <p>
        This website and its content are copyright of Mozer Consulting - © Mozer Consulting {{ now.year }}.
        All rights reserved.
    </p>

    <p>
      Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following:
      <ul>
        <li>You may print or download to a local hard disk extracts for your personal and non-commercial use only</li>
        <li>You may copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material</li>
      </ul>
    </p>

    <p>
      You may not, except with our express written permission, distribute or commercially exploit the content.
      Nor may you transmit it or store it in any other website or other form of electronic retrieval system.
    </p>


</div> <!-- Main container-->
{% endblock %}

{% block footer %}
    {% include 'ws_footer.html' %}
{% endblock %}

myapp/website/templates/ws_disclaimer.html
{% extends "base.html" %}

{% block favicon %}
    <link rel="icon" href="{{ url_for('static', filename='img/logo_moco.ico') }}" type="image/x-icon" />
{% endblock %}

{% block custom_styles %}

{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block title %}Mozer Consulting - Copyright Notice{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block header %}
    {% include 'ws_navbar.html' %}
{% endblock %}

{% block main %}
<div class="container rounded-3 mt-5"> <!-- Main container -->

	<div class="row"> <!-- Row for page title -->
		<div class="col-12 my-2"> <!-- Col for page title -->
			<h3>Disclaimer</h3>
			<hr>
		</div> <!-- Col for page title -->
	</div> <!-- Row for page title -->

    <p>
        The information contained in this website is for general information purposes only. The information is
        provided by Mozer Consulting and while we endeavour to keep the information up to date and correct,
        we make no representations or warranties of any kind, express or implied, about the completeness,
        accuracy, reliability, suitability or availability with respect to the website or the information,
        products, services, or related graphics contained on the website for any purpose. Any reliance you
        place on such information is therefore strictly at your own risk.
    </p>

    <p>
        In no event will we be liable for any loss or damage including without limitation, indirect or
        consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits
        arising out of, or in connection with, the use of this website.
    </p>

    <p>
        Through this website you are able to link to other websites which are not under the control of
        Mozer Consulting. We have no control over the nature, content and availability of those sites.
        The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed
        within them.
    </p>

    <p>
        Every effort is made to keep the website up and running smoothly. However, Mozer Consulting takes no
        responsibility for, and will not be liable for, the website being temporarily unavailable due to technical
        issues beyond our control.
    </p>

    <p>
        SAP is a registered trademark of SAP AG in Germany and many other countries. Mozer Consulting and Mark Mozer
        are not associated with SAP AG in any way.
    </p>

</div> <!-- Main container-->

{% endblock %}

{% block footer %}
    {% include 'ws_footer.html' %}
{% endblock %}

myapp/website/templates/ws_experience.html
<section id="experience">
    <div class="container mt-4">
        <h2 class="mt-4 pb-2 border-bottom"><img class="me-3" src="{{ url_for('static', filename='/img/svg/calendar-check.svg') }}"> Experience</h2>

        <h5 class="pt-3">
            {{ now.year - 2001 }}+ years (international) experience in different lines of business, roles, end-to-end processes and project types.
        </h5>

      <div class="accordion accordion-flush" id="accordionFlushExperience">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseSeven" aria-expanded="false" aria-controls="flush-collapseSeven">
              Employment History
            </button>
          </h2>
          <div id="flush-collapseSeven" class="accordion-collapse collapse">
            <div class="accordion-body">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">From</th>
                      <th scope="col">To</th>
                      <th scope="col">Role</th>
                      <th scope="col">Company</th>
                      <th scope="col">City </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">2018</th>
                      <th>now</th>
                      <td>Freelance SAP Consultant</td>
                      <td>Mozer Consulting</td>
                      <td>De Meern</td>
                    </tr>
                    <tr>
                      <th scope="row">2012</th>
                      <th>2018</th>
                      <td>Managing Consultant</td>
                      <td>Magnus Blue</td>
                      <td>Naarden</td>
                    </tr>
                    <tr>
                      <th scope="row">2009</th>
                      <th>2011</th>
                      <td>Senior Consultant</td>
                      <td>Magnus Blue</td>
                      <td>Naarden</td>
                    </tr>
                    <tr>
                      <th scope="row">2007</th>
                      <th>2009</th>
                      <td>Senior Consultant</td>
                      <td>ITVisors</td>
                      <td>Utrecht</td>
                    </tr>
                    <tr>
                      <th scope="row">2006</th>
                      <th>2007</th>
                      <td>Consultant</td>
                      <td>Accenture Business Services</td>
                      <td>Amsterdam</td>
                    </tr>
                    <tr>
                      <th scope="row">2005</th>
                      <th>2006</th>
                      <td>Inhouse Consultant</td>
                      <td>Unilever</td>
                      <td>Rotterdam</td>
                    </tr>
                    <tr>
                      <th scope="row">2003</th>
                      <th>2004</th>
                      <td>Team lead Planning</td>
                      <td>Unilever</td>
                      <td>Rotterdam</td>
                    </tr>
                    <tr>
                      <th scope="row">2001</th>
                      <th>2003</th>
                      <td>Inhouse Consultant</td>
                      <td>Unilever</td>
                      <td>Rotterdam</td>
                    </tr>
                    <tr>
                      <th scope="row">1999</th>
                      <th>2001</th>
                      <td>Management Trainee</td>
                      <td>Ormit</td>
                      <td>Utrecht</td>
                    </tr>
                    <tr>
                      <th scope="row">1998</th>
                      <th>1999</th>
                      <td>Consultant</td>
                      <td>Baan Business Innovation</td>
                      <td>Ede</td>
                    </tr>
                  </tbody>
                </table>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseEight" aria-expanded="false" aria-controls="flush-collapseEight">
              Companies / Customers
            </button>
          </h2>
          <div id="flush-collapseEight" class="accordion-collapse collapse">
            <div class="accordion-body">
                <div class="row">
                    <!--NXP-->
                    <div class="col-lg-4 my-4">
                        <h6>
                            <img src="{{ url_for('static', filename='/img/logo_nxp.png') }}" alt="NXP logo" height="24" class="mb-2"> NXP Semiconductors
                            <span class="badge text-bg-dark ml-4">High-Tech</span>
                        </h6>
                        <span class="badge text-bg-primary px-1">S/4</span>
                        <span class="badge text-bg-primary px-1">ECC</span><br>
                        <span class="badge text-bg-light px-1">SD</span>
                        <span class="badge text-bg-light px-1">PP-PI</span>
                        <span class="badge text-bg-light px-1">MM</span>
                        <span class="badge text-bg-light px-1">LE</span><br>
                        <span class="badge text-bg-secondary px-1">M&A</span>
                        <span class="badge text-bg-secondary px-1">Brownfield S/4</span><br>
                        <span class="badge text-bg-success px-1">Lead Consultant</span>
                    </div>
                    <!--Teijin Aramid-->
                    <div class="col-lg-4 my-4">
                        <h6>
                            <img src="{{ url_for('static', filename='/img/logo_teijinaramid.png') }}" alt="Teijin Aramid logo" height="24" class="mb-2">
                            <span class="badge text-bg-dark ml-4">Industry</span>
                        </h6>
                        <span class="badge text-bg-primary px-1">S/4</span><br>
                        <span class="badge text-bg-light px-1">MM</span>
                        <span class="badge text-bg-light px-1">LE</span>
                        <span class="badge text-bg-light px-1">TM</span>
                        <span class="badge text-bg-light px-1">SD</span>
                        <span class="badge text-bg-light px-1">PP-PI</span><br>
                        <span class="badge text-bg-secondary px-1">Greenfield S/4</span><br>
                        <span class="badge text-bg-success px-1">Workstream Lead</span>
                    </div>
                    <!--PVH-->
                    <div class="col-lg-4 my-4">
                        <h6>
                            <img src="{{ url_for('static', filename='/img/logo_pvh.png') }}" alt="PVH logo" height="24" class="mb-2"> Phillips-Van Heusen Co.
                            <span class="badge text-bg-dark ml-4">Retail</span>
                        </h6>
                        <span class="badge text-bg-primary px-1">ECC</span><br>
                        <span class="badge text-bg-light px-1">SD</span>
                        <span class="badge text-bg-light px-1">MM</span>
                        <span class="badge text-bg-light px-1">FI</span><br>
                        <span class="badge text-bg-secondary px-1">BREXIT</span><br>
                        <span class="badge text-bg-success px-1">Consultant</span>
                    </div>
                </div>
                <!--Tata Steel-->
                <div class="row">
                    <div class="col-lg-4 my-4">
                        <h6>
                            <img src="{{ url_for('static', filename='/img/logo_tatasteel.png') }}" alt="Tata Steel logo" height="24" class="mb-2">
                            <span class="badge text-bg-dark ml-4">Industry</span>
                        </h6>
                        <span class="badge text-bg-primary px-1">ECC</span><br>
                        <span class="badge text-bg-light px-1">SD</span>
                        <span class="badge text-bg-light px-1">PP</span>
                        <span class="badge text-bg-light px-1">MM</span>
                        <span class="badge text-bg-light px-1">LE</span><br>
                        <span class="badge text-bg-secondary px-1">Harmonization</span>
                        <span class="badge text-bg-secondary px-1">SFC</span><br>
                        <span class="badge text-bg-success px-1">Lead Consultant</span>
                    </div>
                    <!--AkzoNobel-->
                    <div class="col-lg-4 my-4">
                        <h6>
                            <img src="{{ url_for('static', filename='/img/logo_akzonobel.png') }}" alt="AkzoNobel logo" height="24" class="mb-2">
                            <span class="badge text-bg-dark ml-4">Industry</span>
                        </h6>
                        <span class="badge text-bg-primary px-1">ECC</span><br>
                        <span class="badge text-bg-light px-1">SD</span>
                        <span class="badge text-bg-light px-1">MM</span><br>
                        <span class="badge text-bg-secondary px-1">Tax Optimized Supply Chain</span>
                        <span class="badge text-bg-secondary px-1">SAP SLO</span><br>
                        <span class="badge text-bg-success px-1">Lead Consultant</span>

                    </div>
                    <!--Unilever-->
                    <div class="col-lg-4 my-4">
                        <h6>
                            <img src="{{ url_for('static', filename='/img/logo_unilever.png') }}" alt="Unilever logo" height="24" class="mb-2"> Unilever
                            <span class="badge text-bg-dark ml-4">FMCG</span>
                        </h6>
                        <span class="badge text-bg-primary px-1">ECC</span><br>
                        <span class="badge text-bg-light px-1">SD</span>
                        <span class="badge text-bg-light px-1">MM</span>
                        <span class="badge text-bg-light px-1">LE</span>
                        <span class="badge text-bg-light px-1">PP</span><br>
                        <span class="badge text-bg-secondary px-1">European Roll-out</span>
                        <span class="badge text-bg-secondary px-1">Tax Optimized Supply Chain</span><br>
                        <span class="badge text-bg-success px-1">Lead Consultant</span>

                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                    <h6><span class="badge text-bg-dark ml-4">Industry</span></h6>
                        <ul>
                            <li>ASML</li>
                            <li>Evonik</li>
                            <li>Cargotec</li>
                        </ul>
                    </div>
                    <div class="col-lg-4">
                    <h6><span class="badge text-bg-dark ml-4">Services</span></h6>
                        <ul>
                            <li>Koninklijke Jaarbeurs</li>
                            <li>GVB</li>
                            <li>RET</li>
                        </ul>
                    </div>
                    <div class="col-lg-4">
                    <h6><span class="badge text-bg-dark ml-4">Trade</span></h6>
                        <ul>
                            <li>Medeco</li>
                        </ul>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

myapp/website/templates/ws_flash.html
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category: %}
                    <div class="alert alert-{{category}} mb-0" role="alert">
                        {{ message }}
                    </div>
                {% else: %}
                    <div class="alert alert-danger mb-0" role="alert">
                        {{ message }}
                    </div>
                {% endif %}

            {% endfor %}
        {% endif %}
    {% endwith %}

myapp/website/templates/ws_footer.html
<div class="container-fluid bg-dark mt-5 py-5 text-moco-lightgray">
  <div class="container">
    <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5">
      <div class="col mb-3">
        <a href="/" class="d-flex align-items-center mb-3">
          <img class="bi" src="{{ url_for('static', filename='/img/logo_moco_white.png') }}" width="80">
        </a>
        <p>© {{ now.year }} Mozer Consulting</p>
      </div>

    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5 class="text-moco-orange">General</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#top' }}" class="link-moco-lightgray text-decoration-none p-0">Home</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#vision' }}" class="link-moco-lightgray text-decoration-none p-0">Vision</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#mission' }}" class="link-moco-lightgray text-decoration-none p-0">Mission</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#about' }}" class="link-moco-lightgray text-decoration-none p-0">About</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#contact' }}" class="link-moco-lightgray text-decoration-none p-0">Contact</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5 class="text-moco-orange">Detailed</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#expertise' }}" class="link-moco-lightgray text-decoration-none p-0">Expertise</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#experience' }}" class="link-moco-lightgray text-decoration-none p-0">Experience</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#skills' }}" class="link-moco-lightgray text-decoration-none p-0">Skills</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.home') + '#python' }}" class="link-moco-lightgray text-decoration-none p-0">Python+Web</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5 class="text-moco-orange">Legal</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.my_copyright') }}" class="link-moco-lightgray text-decoration-none p-0">Copyright notice</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.disclaimer') }}" class="link-moco-lightgray text-decoration-none p-0">Disclaimer</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.terms') }}" class="link-moco-lightgray text-decoration-none p-0">Terms & Conditions</a></li>
        <li class="nav-item mb-2"><a href="{{ url_for('website_bp.privacy') }}" class="link-moco-lightgray text-decoration-none p-0">Privacy Policy</a></li>
      </ul>
    </div>
  </footer>
    </div>
</div>

myapp/website/templates/ws_hero.html
<section id="hero">
    <div bg-dark" aria-label="Website Hero">
        <img
                class="d-block mx-auto"
                src="{{ url_for('static',filename='/img/artwork_pptd.png') }}"
                alt="Mozer Consulting - frictionless interaction between People, Process, Technology and Data"
                width="100%"
        >
    </div>
</section>

myapp/website/templates/ws_mission.html
<section id="mission">
    <div class="container mt-4">
        <h2 class="mt-4 pb-2 border-bottom"><img class="me-3" src="{{ url_for('static', filename='/img/svg/rocket-takeoff.svg') }}"> Mission</h2>
        <div class="row mb-3">
          <div class="col-md-8 themed-grid-col text-justify">
              <h5>
                  We design, build and deploy innovative IT solutions either in SAP or seamlessly integrated with SAP that
                  simplify and enhance supply chain operations through frictionless interaction between People, Process
                  and Data.
              </h5>
              <br>
              <h5>
                  Together we:
              </h5>
                <h5>
                  <li>Turn your strategy into action.</li>
                  <li>Empower your workforce.</li>
                  <li>Drive sustainable growth and operational excellence.</li>
                </h5>
          </div>
          <div class="col-md-4 themed-grid-col">
              <img src="{{ url_for('static', filename='/img/artwork_synergy.png')}}" width=100%>
          </div>
        </div>
    </div>
</section>